id: f20d2ef8-0196-4646-8348-9d5182bda1a9
inputs:
- description: ""
  key: test1
  required: false
  value: {}
name: nTestPrint
outputs: []
sourceplaybookid: 69977629-e407-4718-870e-52d44e582547
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: e1ccbd58-ef0a-40ee-8e36-bedb37d5fc4b
      iscommand: false
      name: ""
      version: -1
    taskid: e1ccbd58-ef0a-40ee-8e36-bedb37d5fc4b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: ntest
    separatecontext: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 18480a9a-e905-41d5-8a80-9ad9101d7451
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 18480a9a-e905-41d5-8a80-9ad9101d7451
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 260
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 305,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
