id: 8905c594-6f4e-4455-8b65-8a1d4e9581c1
inputs: []
name: PB_Case_01528270_copy
outputs: []
sourceplaybookid: 13c884e3-bb5f-40ff-8c8e-f28e462708b5
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: a289b409-851f-4f52-8a2e-541e5170fac2
      iscommand: false
      name: ""
      version: -1
    taskid: a289b409-851f-4f52-8a2e-541e5170fac2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    scriptarguments:
      listData:
        simple: ${incident.labels.Instance}
      listName:
        simple: List_Case_01528270
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.set
      id: e5486e8b-1cc9-4bf6-8038-301a3007c961
      iscommand: true
      name: Set List
      script: Builtin|||setList
      type: regular
      version: -1
    taskid: e5486e8b-1cc9-4bf6-8038-301a3007c961
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
