id: 8905c594-6f4e-4455-8b65-8a1d4e9581c1
inputs: []
name: PB_Case_01528270_copy
outputs: []
sourceplaybookid: 13c884e3-bb5f-40ff-8c8e-f28e462708b5
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    separatecontext: false
    task:
      brand: ""
      id: a289b409-851f-4f52-8a2e-541e5170fac2
      iscommand: false
      name: ""
      version: -1
    taskid: a289b409-851f-4f52-8a2e-541e5170fac2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    scriptarguments:
      listData:
        simple: tiger
      listName:
        simple: List_Case_01528270
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.set
      id: 30d516ee-7075-4eb2-882b-33b0e5598647
      iscommand: true
      name: Set List
      script: Builtin|||setList
      type: regular
      version: -1
    taskid: 30d516ee-7075-4eb2-882b-33b0e5598647
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    scriptarguments:
      listData:
        simple: '*'
      listName:
        simple: List_Case_01528270
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.set
      id: c9093469-9e74-4b0a-8168-b6a09441f24f
      iscommand: true
      name: Set List *
      script: Builtin|||setList
      type: regular
      version: -1
    taskid: c9093469-9e74-4b0a-8168-b6a09441f24f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    scriptarguments:
      listData:
        simple: monkey
      listName:
        simple: List_Case_01528270
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.add
      id: 8f71b094-d5b7-439c-8e2e-5acffd66bfbd
      iscommand: true
      name: Add to List
      script: Builtin|||addToList
      type: regular
      version: -1
    taskid: 8f71b094-d5b7-439c-8e2e-5acffd66bfbd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
